const productDisplay = {
  'Yorkville Sound YXL12P 12 Inch 1000 Watt Powered Loudspeaker': {
    shortName: 'Yorkville YXL12P Speaker',
    specs: '700W · 12" woofer',
    sku: 'YXL-12P-001',
    rating: 4.8,
    reviews: 32,
    condition: 'Excellent',
    detailSpecs: { Power: '700W RMS', Woofer: '12"', Tweeter: '1.4"', SPL: '128 dB' },
  },
  'Yorkville SoundEXM Mobile Tower Battery Powered PA System': {
    shortName: 'Yorkville EXM Mobile Tower',
    specs: 'Battery powered · portable PA',
    sku: 'EXM-TWR-001',
    rating: 4.6,
    reviews: 18,
    condition: 'Excellent',
    detailSpecs: { Type: 'Column PA', Power: 'Battery', Bluetooth: 'Yes', Weight: '35 lbs' },
  },
  'JBL EON715 15 Inch Powered PA Speaker with Bluetooth': {
    shortName: 'JBL EON715 Speaker',
    specs: '1300W · 15" · Bluetooth',
    sku: 'EON715-001',
    rating: 4.7,
    reviews: 45,
    condition: 'Excellent',
    detailSpecs: { Power: '1300W', Woofer: '15"', Bluetooth: 'Yes', SPL: '132 dB' },
  },
  'QSC K12.2 12 Inch 2000W Powered Loudspeaker': {
    shortName: 'QSC K12.2 Speaker',
    specs: '2000W · 12" · DSP',
    sku: 'K12-2-001',
    rating: 4.9,
    reviews: 67,
    condition: 'Excellent',
    detailSpecs: { Power: '2000W', Woofer: '12"', DSP: 'Advanced', SPL: '132 dB' },
  },
  'JBL PRX418S 18 Inch Passive Subwoofer': {
    shortName: 'JBL PRX418S Subwoofer',
    specs: '800W · 18" passive sub',
    sku: 'PRX418S-001',
    rating: 4.6,
    reviews: 28,
    condition: 'Excellent',
    detailSpecs: { Power: '800W', Driver: '18"', Type: 'Passive', Frequency: '35-250 Hz' },
  },
  'Bose L1 Pro32 Portable Line Array System': {
    shortName: 'Bose L1 Pro32',
    specs: 'Portable line array · 180° coverage',
    sku: 'L1P32-001',
    rating: 4.8,
    reviews: 34,
    condition: 'Excellent',
    detailSpecs: { Coverage: '180°', Type: 'Line array', Bluetooth: 'Yes', RaceTrack: '32 drivers' },
  },
  'Electro-Voice ZLX-12P 12 Inch Two-Way Powered Loudspeaker': {
    shortName: 'EV ZLX-12P Speaker',
    specs: '1000W · 12" powered',
    sku: 'ZLX12P-001',
    rating: 4.5,
    reviews: 52,
    condition: 'Excellent',
    detailSpecs: { Power: '1000W', Woofer: '12"', Tweeter: '1.5"', SPL: '126 dB' },
  },
  'Yorkville Sound Tripod Boom Stand - Black': {
    shortName: 'Yorkville Tripod Stand',
    specs: 'Boom stand · black',
    sku: 'TBS-BLK-001',
    rating: 4.9,
    reviews: 56,
    condition: 'New',
    detailSpecs: { Type: 'Tripod boom', Color: 'Black', 'Max Height': '6.5 ft', Weight: '8 lbs' },
  },
  'Mackie Thump212XT 12 Inch 1400W Enhanced Powered Loudspeaker': {
    shortName: 'Mackie Thump212XT',
    specs: '1400W · 12" · Bluetooth',
    sku: 'TH212XT-001',
    rating: 4.5,
    reviews: 29,
    condition: 'Excellent',
    detailSpecs: { Power: '1400W', Woofer: '12"', Bluetooth: 'Yes', EQ: '3-band + sweep mid' },
  },
  'QSC KS118 18 Inch 3600W Powered Subwoofer': {
    shortName: 'QSC KS118 Subwoofer',
    specs: '3600W · 18" · cardioid capable',
    sku: 'KS118-001',
    rating: 4.9,
    reviews: 22,
    condition: 'Excellent',
    detailSpecs: { Power: '3600W', Driver: '18"', Mode: 'Cardioid capable', Weight: '108 lbs' },
  },
  'Shure SM58 Unidirectional/Cardioid Dynamic Microphone': {
    shortName: 'Shure SM58 Microphone',
    specs: 'Cardioid dynamic · unidirectional',
    sku: 'SM58-001',
    rating: 4.9,
    reviews: 128,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dynamic', Pattern: 'Cardioid', Frequency: '50-15,000 Hz', Impedance: '150Ω' },
  },
  'Shure SM57 Instrument Microphone': {
    shortName: 'Shure SM57 Mic',
    specs: 'Cardioid dynamic · instrument',
    sku: 'SM57-001',
    rating: 4.9,
    reviews: 142,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dynamic', Pattern: 'Cardioid', Frequency: '40-15,000 Hz', Use: 'Instrument/vocal' },
  },
  'Sennheiser e835 Evolution Handheld Cardioid Microphone': {
    shortName: 'Sennheiser e835 Mic',
    specs: 'Cardioid dynamic · handheld',
    sku: 'E835-001',
    rating: 4.6,
    reviews: 34,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dynamic', Pattern: 'Cardioid', Frequency: '40-16,000 Hz', Brand: 'Sennheiser' },
  },
  'Sennheiser EW 112-P G4-A Portable Lavalier Set': {
    shortName: 'Sennheiser EW 112-P G4',
    specs: 'Lavalier · wireless UHF',
    sku: 'EW112-G4-001',
    rating: 4.8,
    reviews: 41,
    condition: 'Excellent',
    detailSpecs: { Type: 'Lavalier wireless', Band: 'UHF (516-558 MHz)', Range: '100m line of sight', Battery: '8 hrs (AA)' },
  },
  'Shure BLX288/PG58 Dual Channel Handheld Wireless System': {
    shortName: 'Shure BLX288 Dual Wireless',
    specs: 'Dual handheld · UHF wireless',
    sku: 'BLX288-001',
    rating: 4.7,
    reviews: 56,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dual wireless', Mics: '2x PG58', Band: 'UHF', Range: '100m line of sight' },
  },
  'Shure GLXD14+/85 Digital Wireless Lavalier System': {
    shortName: 'Shure GLXD14+/85 Wireless',
    specs: 'Digital wireless · lavalier · dual-band',
    sku: 'GLXD14-85-001',
    rating: 4.8,
    reviews: 28,
    condition: 'Excellent',
    detailSpecs: { Type: 'Digital wireless lavalier', Band: '2.4 GHz / 5.8 GHz', Battery: '12 hrs rechargeable', Mic: 'WL185 lavalier' },
  },
  'Audio-Technica AT2020 Cardioid Condenser Microphone': {
    shortName: 'Audio-Technica AT2020',
    specs: 'Cardioid condenser · studio',
    sku: 'AT2020-001',
    rating: 4.7,
    reviews: 89,
    condition: 'Excellent',
    detailSpecs: { Type: 'Condenser', Pattern: 'Cardioid', Frequency: '20-20,000 Hz', 'Max SPL': '144 dB' },
  },
  'Sennheiser XSW 1-835-A Wireless Handheld Microphone System': {
    shortName: 'Sennheiser XSW 1-835',
    specs: 'Wireless handheld · UHF',
    sku: 'XSW1-835-001',
    rating: 4.5,
    reviews: 31,
    condition: 'Excellent',
    detailSpecs: { Type: 'Wireless handheld', Capsule: 'e835', Band: 'UHF (548-572 MHz)', Range: '75m' },
  },
  'Shure CVB-B/O Omnidirectional Installed Boundary Microphone': {
    shortName: 'Shure CVB Boundary Mic',
    specs: 'Omnidirectional · boundary',
    sku: 'CVB-BO-001',
    rating: 4.3,
    reviews: 11,
    condition: 'Excellent',
    detailSpecs: { Type: 'Condenser', Pattern: 'Omnidirectional', Cable: '12 ft', Mount: 'Boundary' },
  },
  'Apex Compact Boundary Microphone': {
    shortName: 'Apex Boundary Mic',
    specs: 'Compact · boundary condenser',
    sku: 'APX-BND-001',
    rating: 4.1,
    reviews: 7,
    condition: 'Used',
    detailSpecs: { Type: 'Condenser', Pattern: 'Hemispherical', Size: 'Compact', Color: 'Black' },
  },
  'AKG P220 Large Diaphragm Condenser Microphone': {
    shortName: 'AKG P220 Condenser',
    specs: 'Large diaphragm · condenser',
    sku: 'P220-001',
    rating: 4.6,
    reviews: 37,
    condition: 'Excellent',
    detailSpecs: { Type: 'Condenser', Pattern: 'Cardioid', Diaphragm: '1"', 'Max SPL': '155 dB' },
  },
  'Mackie ProFX16v3 16-Channel Professional Effects Mixer': {
    shortName: 'Mackie ProFX16v3 Mixer',
    specs: '16 channel · USB · effects',
    sku: 'PFX16V3-001',
    rating: 4.7,
    reviews: 38,
    condition: 'Excellent',
    detailSpecs: { Channels: '16', Type: 'Analog + USB', Effects: 'Built-in GigFX', Preamps: 'Onyx' },
  },
  'Yorkville 8-Channel Passive Mixer': {
    shortName: 'Yorkville 8-Ch Mixer',
    specs: '8 channel · passive',
    sku: 'PGM8-001',
    rating: 4.4,
    reviews: 16,
    condition: 'Excellent',
    detailSpecs: { Channels: '8', Type: 'Passive', Model: 'PGM8', Aux: '1 send' },
  },
  'Yorkville 14-Channel Compact Desk Mixer': {
    shortName: 'Yorkville 14-Ch Mixer',
    specs: '14 channel · compact desk',
    sku: 'VGM14-001',
    rating: 4.5,
    reviews: 23,
    condition: 'Excellent',
    detailSpecs: { Channels: '14', Type: 'Analog desk', Model: 'VGM14', EQ: '3-band' },
  },
  'Allen & Heath ZED-12FX 12-Channel Mixer with Effects': {
    shortName: 'Allen & Heath ZED-12FX',
    specs: '12 channel · effects · USB',
    sku: 'ZED12FX-001',
    rating: 4.6,
    reviews: 25,
    condition: 'Excellent',
    detailSpecs: { Channels: '12', Effects: 'Built-in', USB: 'Yes', EQ: '3-band MusiQ' },
  },
  'Yamaha MG20XU 20-Channel Mixer with Effects and USB': {
    shortName: 'Yamaha MG20XU Mixer',
    specs: '20 channel · SPX effects · USB',
    sku: 'MG20XU-001',
    rating: 4.7,
    reviews: 34,
    condition: 'Excellent',
    detailSpecs: { Channels: '20', Effects: 'SPX digital', USB: '2.0', Preamps: 'D-PRE' },
  },
  'Yorkville 24 Channel x 4 XLR Returns - 100 foot': {
    shortName: 'Yorkville 24-Ch Snake',
    specs: '24 channel · 100 ft XLR',
    sku: 'SNK24-100-001',
    rating: 4.7,
    reviews: 12,
    condition: 'Excellent',
    detailSpecs: { Channels: '24 send / 4 return', Length: '100 ft', Connectors: 'XLR', Weight: '32 lbs' },
  },
  'Radial ProDI Passive Direct Box': {
    shortName: 'Radial ProDI',
    specs: 'Passive DI · transformer coupled',
    sku: 'PRODI-001',
    rating: 4.8,
    reviews: 44,
    condition: 'Excellent',
    detailSpecs: { Type: 'Passive DI', Transformer: 'Custom', Pad: '-15 dB', Ground: 'Lift switch' },
  },
  'Furman M-8x2 Merit Series 8 Outlet Power Conditioner': {
    shortName: 'Furman M-8x2 Power Conditioner',
    specs: '8 outlet · surge protection',
    sku: 'M8X2-001',
    rating: 4.5,
    reviews: 21,
    condition: 'Excellent',
    detailSpecs: { Outlets: '8 rear', Protection: 'SMP+', Voltage: '120V', Mount: '1U rack' },
  },
  'Behringer Powerplay P16-M 16-Channel Digital Personal Mixer': {
    shortName: 'Behringer P16-M Personal Mixer',
    specs: '16 channel · digital · personal',
    sku: 'P16M-001',
    rating: 4.3,
    reviews: 19,
    condition: 'Excellent',
    detailSpecs: { Channels: '16', Type: 'Digital', Network: 'Ultranet', Mount: 'Mic stand / table' },
  },
  'Epson PowerLite 2140W WXGA 3LCD Projector': {
    shortName: 'Epson PowerLite 2140W',
    specs: '4,200 lm · WXGA 1280×800',
    sku: 'EPJ-2140-001',
    rating: 4.5,
    reviews: 24,
    condition: 'Excellent',
    detailSpecs: { Brightness: '4,200 lm', Resolution: 'WXGA 1280×800', Technology: '3LCD', Contrast: '15,000:1' },
  },
  'Grandview 80 Inch X-Press Pull-Up Projector Screen': {
    shortName: 'Grandview 80" Screen',
    specs: '80" · pull-up portable',
    sku: 'GV-80-001',
    rating: 4.4,
    reviews: 15,
    condition: 'Excellent',
    detailSpecs: { Size: '80"', Type: 'Pull-up', Format: '16:9', Surface: 'Matte white' },
  },
  'Grandview Cyber X-Press Series Pull-Up Projector Screen - 92"': {
    shortName: 'Grandview 92" Screen',
    specs: '92" · pull-up portable',
    sku: 'GV-92-001',
    rating: 4.5,
    reviews: 19,
    condition: 'Excellent',
    detailSpecs: { Size: '92"', Type: 'Pull-up', Series: 'Cyber X-Press', Surface: 'Matte white' },
  },
  'Zoom Q8N Handheld 4K Video and Audio Recorder': {
    shortName: 'Zoom Q8N-4K Recorder',
    specs: '4K video · XY stereo mic',
    sku: 'ZM-Q8N-001',
    rating: 4.7,
    reviews: 22,
    condition: 'Excellent',
    detailSpecs: { Video: '4K/30fps', Audio: 'XY stereo mic', Storage: 'microSD', Battery: '2 hrs' },
  },
  'Epson PowerLite 1795F Full HD Wireless 3LCD Projector': {
    shortName: 'Epson PowerLite 1795F',
    specs: '3,200 lm · Full HD · wireless',
    sku: 'EPJ-1795F-001',
    rating: 4.6,
    reviews: 18,
    condition: 'Excellent',
    detailSpecs: { Brightness: '3,200 lm', Resolution: '1080p Full HD', Wireless: 'Built-in', Weight: '3.9 lbs' },
  },
  'Chauvet DJ SlimPAR Pro H USB RGBAW+UV LED Wash Light': {
    shortName: 'Chauvet SlimPAR Pro H',
    specs: 'RGBAW+UV · DMX · USB',
    sku: 'SLMPRH-001',
    rating: 4.6,
    reviews: 42,
    condition: 'Excellent',
    detailSpecs: { LEDs: '12x 10W RGBAW+UV', DMX: 'Yes', Modes: '6-channel', Power: '138W' },
  },
  'ADJ Mega HEX Par RGBAW+UV LED Par Light': {
    shortName: 'ADJ Mega HEX Par',
    specs: 'RGBAW+UV · compact LED par',
    sku: 'MHPAR-001',
    rating: 4.4,
    reviews: 33,
    condition: 'Excellent',
    detailSpecs: { LEDs: '5x 6-in-1 HEX', Colors: 'RGBAW+UV', DMX: 'Yes', Weight: '3.5 lbs' },
  },
  'Chauvet Intimidator Spot 360 LED Moving Head': {
    shortName: 'Chauvet Intimidator 360',
    specs: '100W LED moving head spot',
    sku: 'INT360-001',
    rating: 4.7,
    reviews: 26,
    condition: 'Excellent',
    detailSpecs: { Power: '100W LED', Type: 'Moving head spot', Pan: '540°', Tilt: '270°' },
  },
  'Chauvet DJ Hurricane Haze 2D Water-Based Hazer': {
    shortName: 'Chauvet Hurricane Haze 2D',
    specs: 'Water-based hazer · DMX',
    sku: 'HH2D-001',
    rating: 4.5,
    reviews: 31,
    condition: 'Excellent',
    detailSpecs: { Type: 'Water-based hazer', Output: '2,600 cfm', DMX: 'Yes', Timer: 'Built-in' },
  },
  'ADJ Fog Storm 1200HD Fog Machine': {
    shortName: 'ADJ Fog Storm 1200HD',
    specs: '1200W · wired & wireless remote',
    sku: 'FS1200-001',
    rating: 4.3,
    reviews: 22,
    condition: 'Excellent',
    detailSpecs: { Power: '1200W', Output: '28,000 cfm', Tank: '2.5L', 'Heat-up': '5.5 min' },
  },
  'Chauvet DJ GigBAR Move 5-in-1 Lighting System': {
    shortName: 'Chauvet GigBAR Move',
    specs: '5-in-1 · moving heads + pars + laser + strobe',
    sku: 'GBMV-001',
    rating: 4.8,
    reviews: 37,
    condition: 'Excellent',
    detailSpecs: { Fixtures: '2 moving heads + 2 pars + laser + strobe', DMX: 'Yes', Modes: 'Sound active / auto', Stand: 'Included' },
  },
  'ADJ Ultra Bar 12H RGBAW+UV LED Linear Fixture': {
    shortName: 'ADJ Ultra Bar 12H',
    specs: '12x 10W RGBAW+UV linear bar',
    sku: 'UB12H-001',
    rating: 4.5,
    reviews: 18,
    condition: 'Excellent',
    detailSpecs: { LEDs: '12x 10W', Colors: 'RGBAW+UV', Length: '40"', DMX: '3/5/8/12 channel' },
  },
  'Chauvet DJ Obey 70 DMX Controller': {
    shortName: 'Chauvet Obey 70 DMX',
    specs: '384 channels · 12 fixtures',
    sku: 'OBEY70-001',
    rating: 4.4,
    reviews: 20,
    condition: 'Excellent',
    detailSpecs: { Channels: '384', Fixtures: '12', Faders: '8', Programs: '30' },
  },
  'ADJ Lighting Stand Package with T-Bar': {
    shortName: 'ADJ Lighting T-Bar Stand',
    specs: 'Tripod stand + T-bar · 12 ft',
    sku: 'LSTB-001',
    rating: 4.6,
    reviews: 25,
    condition: 'Excellent',
    detailSpecs: { 'Max Height': '12 ft', 'T-Bar': '4.8 ft', Capacity: '110 lbs', Type: 'Tripod' },
  },
  'Pioneer DDJ-FLX6 4-Channel DJ Controller': {
    shortName: 'Pioneer DDJ-FLX6',
    specs: '4-channel · Serato/rekordbox',
    sku: 'FLX6-001',
    rating: 4.6,
    reviews: 33,
    condition: 'Excellent',
    detailSpecs: { Channels: '4', Software: 'Serato DJ Pro / rekordbox', Jog: 'Large jog wheels', Effects: 'Merge FX' },
  },
  'Pioneer CDJ-2000NXS2 Professional Multi Player': {
    shortName: 'Pioneer CDJ-2000NXS2',
    specs: 'Pro DJ media player · 7" touchscreen',
    sku: 'CDJ2K-001',
    rating: 4.9,
    reviews: 52,
    condition: 'Excellent',
    detailSpecs: { Screen: '7" touch', Formats: 'USB/SD/Wi-Fi/LAN', Audio: '96 kHz/24-bit', MIDI: 'Yes' },
  },
  'Pioneer DJM-900NXS2 4-Channel Professional DJ Mixer': {
    shortName: 'Pioneer DJM-900NXS2',
    specs: '4-channel · 64-bit mixing · FX',
    sku: 'DJM900-001',
    rating: 4.9,
    reviews: 48,
    condition: 'Excellent',
    detailSpecs: { Channels: '4', Processing: '64-bit', Effects: '14 beat FX', USB: 'Dual' },
  },
  'Pioneer DDJ-1000 4-Channel Performance DJ Controller': {
    shortName: 'Pioneer DDJ-1000',
    specs: '4-channel · full-size jogs · rekordbox',
    sku: 'DDJ1K-001',
    rating: 4.8,
    reviews: 41,
    condition: 'Excellent',
    detailSpecs: { Channels: '4', Jog: 'CDJ-size · on-jog display', Software: 'rekordbox', FX: '14 beat FX' },
  },
  'Technics SL-1200MK7 Direct Drive Turntable': {
    shortName: 'Technics SL-1200MK7',
    specs: 'Direct drive · DJ turntable',
    sku: 'SL1200-001',
    rating: 4.9,
    reviews: 29,
    condition: 'Excellent',
    detailSpecs: { Drive: 'Direct drive', Torque: 'High starting', Speed: '33/45/78 RPM', 'S/N': '> 50 dB' },
  },
  'Pioneer DJM-V10 6-Channel Professional DJ Mixer': {
    shortName: 'Pioneer DJM-V10',
    specs: '6-channel · 4-band EQ · compressor',
    sku: 'DJMV10-001',
    rating: 4.9,
    reviews: 38,
    condition: 'Excellent',
    detailSpecs: { Channels: '6', EQ: '4-band', Effects: 'Send FX + beat FX', Audio: '96 kHz/32-bit' },
  },
  'Pioneer DJM-A9 4-Channel Professional DJ Mixer': {
    shortName: 'Pioneer DJM-A9',
    specs: '4-channel · Bluetooth · touch FX',
    sku: 'DJMA9-001',
    rating: 4.9,
    reviews: 27,
    condition: 'Excellent',
    detailSpecs: { Channels: '4', Bluetooth: 'Yes', Effects: 'Touch FX + beat FX', USB: 'Dual' },
  },
  'Pioneer DJM-S11 Professional 2-Channel DJ Mixer': {
    shortName: 'Pioneer DJM-S11',
    specs: '2-channel · scratch · touchscreen',
    sku: 'DJMS11-001',
    rating: 4.8,
    reviews: 34,
    condition: 'Excellent',
    detailSpecs: { Channels: '2', Screen: '4.3" touch', Magvel: 'Pro crossfader', Software: 'Serato DJ Pro' },
  },
  'Rane ONE Professional Motorized DJ Controller': {
    shortName: 'Rane ONE',
    specs: 'Motorized platters · Serato · standalone',
    sku: 'RANE1-001',
    rating: 4.8,
    reviews: 42,
    condition: 'Excellent',
    detailSpecs: { Platters: '7.2" motorized', Software: 'Serato DJ Pro', Channels: '2', FX: '16 FX paddles' },
  },
  'Rane SEVENTY-TWO MKII Premium 2-Channel Mixer': {
    shortName: 'Rane SEVENTY-TWO MKII',
    specs: '2-channel · 4.3" touchscreen · MAG FOUR fader',
    sku: 'R72MK2-001',
    rating: 4.9,
    reviews: 31,
    condition: 'Excellent',
    detailSpecs: { Channels: '2', Screen: '4.3" touch', Fader: 'MAG FOUR', Software: 'Serato DJ Pro' },
  },
  'Rane TWELVE MKII 12-Inch Motorized Turntable Controller': {
    shortName: 'Rane TWELVE MKII',
    specs: '12" motorized platter · true vinyl feel',
    sku: 'R12MK2-001',
    rating: 4.8,
    reviews: 26,
    condition: 'Excellent',
    detailSpecs: { Platter: '12" motorized', Torque: 'Adjustable', MIDI: 'Yes', Weight: '11.6 lbs' },
  },
  'Pioneer CDJ-3000 Professional DJ Multi Player': {
    shortName: 'Pioneer CDJ-3000',
    specs: 'Pro multi player · 9" touchscreen · MPU',
    sku: 'CDJ3K-001',
    rating: 4.9,
    reviews: 46,
    condition: 'Excellent',
    detailSpecs: { Screen: '9" touch HD', MPU: 'Dedicated', Audio: '96 kHz/32-bit', Storage: 'USB/SD/LAN' },
  },
  'Pioneer DDJ-REV7 Scratch-Style 2-Channel DJ Controller': {
    shortName: 'Pioneer DDJ-REV7',
    specs: '2-channel · motorized jogs · Serato',
    sku: 'REV7-001',
    rating: 4.7,
    reviews: 29,
    condition: 'Excellent',
    detailSpecs: { Jog: '7" motorized', Screens: 'On-jog displays', Software: 'Serato DJ Pro', Fader: 'Magvel' },
  },
  'Rane FOUR Advanced 4-Channel Stems DJ Controller': {
    shortName: 'Rane FOUR',
    specs: '4-channel · Stems · 8.5" platters',
    sku: 'RANE4-001',
    rating: 4.8,
    reviews: 19,
    condition: 'Excellent',
    detailSpecs: { Channels: '4', Platters: '8.5" motorized', Stems: 'Real-time', Software: 'Serato DJ Pro' },
  },
  "Fender '65 Twin Reverb Reissue Guitar Amplifier": {
    shortName: 'Fender Twin Reverb',
    specs: '85W · 2x12" · tube',
    sku: 'FTR65-001',
    rating: 4.9,
    reviews: 38,
    condition: 'Excellent',
    detailSpecs: { Power: '85W', Speakers: '2x 12" Jensen', Tubes: '4x 6L6 / 4x 12AX7', Reverb: 'Spring' },
  },
  'Marshall JCM800 2203 100W Tube Head': {
    shortName: 'Marshall JCM800 Head',
    specs: '100W · tube · legendary tone',
    sku: 'JCM800-001',
    rating: 4.8,
    reviews: 27,
    condition: 'Excellent',
    detailSpecs: { Power: '100W', Tubes: '4x EL34 / 3x ECC83', Channels: '1', EQ: '3-band + presence' },
  },
  'Ampeg SVT-CL Classic 300W All-Tube Bass Head': {
    shortName: 'Ampeg SVT-CL Bass Head',
    specs: '300W · all-tube · classic SVT',
    sku: 'SVTCL-001',
    rating: 4.9,
    reviews: 31,
    condition: 'Excellent',
    detailSpecs: { Power: '300W', Tubes: '6x 6550 / 3x 12AX7 / 1x 12AU7', EQ: '3-band + Ultra', Weight: '85 lbs' },
  },
  'Ampeg SVT-810E 8x10 Bass Cabinet': {
    shortName: 'Ampeg SVT-810E Cab',
    specs: '8x10" · 800W · sealed',
    sku: 'SVT810-001',
    rating: 4.8,
    reviews: 25,
    condition: 'Excellent',
    detailSpecs: { Speakers: '8x 10"', Power: '800W RMS', Impedance: '4Ω', Type: 'Sealed' },
  },
  'Nord Stage 3 88 Weighted Key Stage Keyboard': {
    shortName: 'Nord Stage 3 88',
    specs: '88 weighted keys · piano/organ/synth',
    sku: 'NS388-001',
    rating: 4.9,
    reviews: 24,
    condition: 'Excellent',
    detailSpecs: { Keys: '88 weighted hammer', Sections: 'Piano / Organ / Synth', Memory: '2 GB', Weight: '42 lbs' },
  },
  'Yamaha CP88 Stage Piano': {
    shortName: 'Yamaha CP88 Piano',
    specs: '88 keys · Natural Wood graded',
    sku: 'CP88-001',
    rating: 4.8,
    reviews: 32,
    condition: 'Excellent',
    detailSpecs: { Keys: '88 NW-GH3', Voices: '57', Effects: 'VCM', Weight: '40.8 lbs' },
  },
  'Roland RD-2000 Stage Piano': {
    shortName: 'Roland RD-2000',
    specs: '88 keys · PHA-50 · dual engine',
    sku: 'RD2000-001',
    rating: 4.8,
    reviews: 21,
    condition: 'Excellent',
    detailSpecs: { Keys: '88 PHA-50', Engines: 'V-Piano + SuperNATURAL', Zones: '8', USB: 'Audio + MIDI' },
  },
  "DW Collector's Series 5-Piece Drum Kit": {
    shortName: 'DW Collector\'s Drum Kit',
    specs: '5-piece · maple · pro grade',
    sku: 'DWCS5-001',
    rating: 4.9,
    reviews: 16,
    condition: 'Excellent',
    detailSpecs: { Pieces: '5 (kick/snare/3 toms)', Shell: 'Maple', Hardware: 'DW 9000', Heads: 'Remo' },
  },
  'Roland TD-17KVX V-Drums Electronic Drum Kit': {
    shortName: 'Roland TD-17KVX E-Drums',
    specs: 'Electronic kit · mesh heads · Bluetooth',
    sku: 'TD17KVX-001',
    rating: 4.7,
    reviews: 28,
    condition: 'Excellent',
    detailSpecs: { Module: 'TD-17', Pads: 'Mesh heads', Kits: '50 preset', Bluetooth: 'Yes' },
  },
  "Fender Deluxe Reverb '68 Custom Guitar Amplifier": {
    shortName: "Fender '68 Deluxe Reverb",
    specs: '22W · 1x12" · tube',
    sku: 'F68DR-001',
    rating: 4.8,
    reviews: 33,
    condition: 'Excellent',
    detailSpecs: { Power: '22W', Speaker: '1x 12" Celestion', Tubes: '2x 6V6 / 4x 12AX7', Channels: '2' },
  },
  'Keyboard X-Stand Double Braced': {
    shortName: 'Keyboard X-Stand',
    specs: 'Double braced · adjustable',
    sku: 'KXS-001',
    rating: 4.5,
    reviews: 42,
    condition: 'Excellent',
    detailSpecs: { Type: 'X-style', Bracing: 'Double', 'Max Load': '150 lbs', Adjustable: '5 positions' },
  },
  'Focusrite Scarlett 18i20 3rd Gen USB Audio Interface': {
    shortName: 'Focusrite 18i20 Interface',
    specs: '18-in/20-out · USB-C · ADAT',
    sku: 'SC18I20-001',
    rating: 4.7,
    reviews: 35,
    condition: 'Excellent',
    detailSpecs: { Inputs: '18', Outputs: '20', Connection: 'USB-C', 'Sample Rate': 'Up to 192 kHz' },
  },
  'Yamaha HS8 8-Inch Powered Studio Monitor (Pair)': {
    shortName: 'Yamaha HS8 Monitors (Pair)',
    specs: '8" woofer · 75W bi-amp (each)',
    sku: 'HS8PR-001',
    rating: 4.8,
    reviews: 67,
    condition: 'Excellent',
    detailSpecs: { Woofer: '8"', Tweeter: '1"', Power: '75W LF + 45W HF', Response: '38 Hz - 30 kHz' },
  },
  'Beyerdynamic DT 770 Pro 250 Ohm Studio Headphones': {
    shortName: 'Beyerdynamic DT 770 Pro',
    specs: 'Closed · 250 Ohm · velour',
    sku: 'DT770-001',
    rating: 4.8,
    reviews: 88,
    condition: 'Excellent',
    detailSpecs: { Type: 'Closed-back', Impedance: '250 Ω', Response: '5-35,000 Hz', Comfort: 'Velour pads' },
  },
  'Focusrite Scarlett 2i2 3rd Gen USB Audio Interface': {
    shortName: 'Focusrite 2i2 Interface',
    specs: '2-in/2-out · USB-C · compact',
    sku: 'SC2I2-001',
    rating: 4.7,
    reviews: 112,
    condition: 'Excellent',
    detailSpecs: { Inputs: '2', Outputs: '2', Connection: 'USB-C', Preamps: 'Air mode' },
  },
  'KRK ROKIT 5 G4 5-Inch Powered Studio Monitor (Pair)': {
    shortName: 'KRK ROKIT 5 G4 (Pair)',
    specs: '5" woofer · 55W bi-amp (each)',
    sku: 'KRK5G4-001',
    rating: 4.5,
    reviews: 54,
    condition: 'Excellent',
    detailSpecs: { Woofer: '5"', Tweeter: '1"', Power: '55W total', DSP: 'Room correction' },
  },
};

export function getDisplayData(product) {
  return productDisplay[product] || {
    shortName: product.split(' ').slice(0, 3).join(' '),
    specs: '',
    sku: null,
    rating: null,
    reviews: 0,
    condition: null,
    detailSpecs: {},
  };
}

export function getShortName(product) {
  return getDisplayData(product).shortName;
}

export function getWeeklyRate(dailyRate) {
  if (!dailyRate) return null;
  return dailyRate * 4;
}
