const productDisplay = {
  'Yorkville Sound YXL12P 12 Inch 1000 Watt Powered Loudspeaker': {
    shortName: 'Yorkville YXL12P Speaker',
    specs: '700W · 12" woofer',
    sku: 'YXL-12P-001',
    rating: 4.8,
    reviews: 32,
    condition: 'Excellent',
    detailSpecs: { Power: '700W RMS', Woofer: '12"', Tweeter: '1.4"', SPL: '128 dB' },
  },
  'Yorkville SoundEXM Mobile Tower Battery Powered PA System': {
    shortName: 'Yorkville EXM Mobile Tower',
    specs: 'Battery powered · portable PA',
    sku: 'EXM-TWR-001',
    rating: 4.6,
    reviews: 18,
    condition: 'Excellent',
    detailSpecs: { Type: 'Column PA', Power: 'Battery', Bluetooth: 'Yes', Weight: '35 lbs' },
  },
  'Yorkville Sound Tripod Boom Stand - Black': {
    shortName: 'Yorkville Tripod Stand',
    specs: 'Boom stand · black',
    sku: 'TBS-BLK-001',
    rating: 4.9,
    reviews: 56,
    condition: 'New',
    detailSpecs: { Type: 'Tripod boom', Color: 'Black', 'Max Height': '6.5 ft', Weight: '8 lbs' },
  },
  'Epson PowerLite 2140W WXGA 3LCD Projector': {
    shortName: 'Epson PowerLite 2140W',
    specs: '4,200 lm · WXGA 1280×800',
    sku: 'EPJ-2140-001',
    rating: 4.5,
    reviews: 24,
    condition: 'Excellent',
    detailSpecs: { Brightness: '4,200 lm', Resolution: 'WXGA 1280×800', Technology: '3LCD', Contrast: '15,000:1' },
  },
  '135in 10x6 projector screen': {
    shortName: '135" Projector Screen',
    specs: '10×6 ft · pull-up',
    sku: 'SCR-135-001',
    rating: 4.3,
    reviews: 8,
    condition: 'Used',
    detailSpecs: { Size: '135"', Dimensions: '10×6 ft', Type: 'Pull-up', Format: '16:9' },
  },
  'Grandview 80 Inch X-Press Pull-Up Projector Screen': {
    shortName: 'Grandview 80" Screen',
    specs: '80" · pull-up portable',
    sku: 'GV-80-001',
    rating: 4.4,
    reviews: 15,
    condition: 'Excellent',
    detailSpecs: { Size: '80"', Type: 'Pull-up', Format: '16:9', Surface: 'Matte white' },
  },
  'Grandview Cyber X-Press Series Pull-Up Projector Screen - 92"': {
    shortName: 'Grandview 92" Screen',
    specs: '92" · pull-up portable',
    sku: 'GV-92-001',
    rating: 4.5,
    reviews: 19,
    condition: 'Excellent',
    detailSpecs: { Size: '92"', Type: 'Pull-up', Series: 'Cyber X-Press', Surface: 'Matte white' },
  },
  'Zoom Q8N Handheld 4K video and audio Recorder': {
    shortName: 'Zoom Q8N-4K Recorder',
    specs: '4K video · XY stereo mic',
    sku: 'ZM-Q8N-001',
    rating: 4.7,
    reviews: 22,
    condition: 'Excellent',
    detailSpecs: { Video: '4K/30fps', Audio: 'XY stereo mic', Storage: 'microSD', Battery: '2 hrs' },
  },
  'Shure SM58 Unidirectional/Cardioid Dynamic Microphone': {
    shortName: 'Shure SM58 Microphone',
    specs: 'Cardioid dynamic · unidirectional',
    sku: 'SM58-001',
    rating: 4.9,
    reviews: 128,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dynamic', Pattern: 'Cardioid', Frequency: '50-15,000 Hz', Impedance: '150Ω' },
  },
  'Shure e835 Evolution Handheld Cardioid Microphone': {
    shortName: 'Sennheiser e835 Mic',
    specs: 'Cardioid dynamic · handheld',
    sku: 'E835-001',
    rating: 4.6,
    reviews: 34,
    condition: 'Excellent',
    detailSpecs: { Type: 'Dynamic', Pattern: 'Cardioid', Frequency: '40-16,000 Hz', Brand: 'Sennheiser' },
  },
  'Shure CVB-B/O Omnidirectional Installed Boundary Microphone': {
    shortName: 'Shure CVB Boundary Mic',
    specs: 'Omnidirectional · boundary',
    sku: 'CVB-BO-001',
    rating: 4.3,
    reviews: 11,
    condition: 'Excellent',
    detailSpecs: { Type: 'Condenser', Pattern: 'Omnidirectional', Cable: '12 ft', Mount: 'Boundary' },
  },
  'Apex Compact Boundary Microphone': {
    shortName: 'Apex Boundary Mic',
    specs: 'Compact · boundary condenser',
    sku: 'APX-BND-001',
    rating: 4.1,
    reviews: 7,
    condition: 'Used',
    detailSpecs: { Type: 'Condenser', Pattern: 'Hemispherical', Size: 'Compact', Color: 'Black' },
  },
  'Sennheiser EW 112-P G4-A Portable Lavalier Set': {
    shortName: 'Sennheiser EW 112-P G4',
    specs: 'Lavalier · wireless UHF',
    sku: 'EW112-G4-001',
    rating: 4.8,
    reviews: 41,
    condition: 'Excellent',
    detailSpecs: { Type: 'Lavalier wireless', Band: 'UHF (516-558 MHz)', Range: '100m line of sight', Battery: '8 hrs (AA)' },
  },
  'Podium mic (model TBD)': {
    shortName: 'Podium Microphone',
    specs: 'Gooseneck · podium mount',
    sku: 'POD-MIC-TBD',
    rating: null,
    reviews: 0,
    condition: 'TBD',
    detailSpecs: { Type: 'Gooseneck', Mount: 'Podium', Status: 'Model TBD' },
  },
  'Yorkville 8-Channel Passive Mixer': {
    shortName: 'Yorkville 8-Ch Mixer',
    specs: '8 channel · passive',
    sku: 'PGM8-001',
    rating: 4.4,
    reviews: 16,
    condition: 'Excellent',
    detailSpecs: { Channels: '8', Type: 'Passive', Model: 'PGM8', Aux: '1 send' },
  },
  'Yorkville 14-Channel Compact Desk Mixer': {
    shortName: 'Yorkville 14-Ch Mixer',
    specs: '14 channel · compact desk',
    sku: 'VGM14-001',
    rating: 4.5,
    reviews: 23,
    condition: 'Excellent',
    detailSpecs: { Channels: '14', Type: 'Analog desk', Model: 'VGM14', EQ: '3-band' },
  },
  'Yorkville 24 Channel x 4 XLR Returns - 100 foot': {
    shortName: 'Yorkville 24-Ch Snake',
    specs: '24 channel · 100 ft XLR',
    sku: 'SNK24-100-001',
    rating: 4.7,
    reviews: 12,
    condition: 'Excellent',
    detailSpecs: { Channels: '24 send / 4 return', Length: '100 ft', Connectors: 'XLR', Weight: '32 lbs' },
  },
  'Mackie ProFX16v3 16-Channel Professional Effects Mixer': {
    shortName: 'Mackie ProFX16v3 Mixer',
    specs: '16 channel · USB · effects',
    sku: 'PFX16V3-001',
    rating: 4.7,
    reviews: 38,
    condition: 'Excellent',
    detailSpecs: { Channels: '16', Type: 'Analog + USB', Effects: 'Built-in GigFX', Preamps: 'Onyx' },
  },
};

export function getDisplayData(product) {
  return productDisplay[product] || {
    shortName: product.split(' ').slice(0, 3).join(' '),
    specs: '',
    sku: null,
    rating: null,
    reviews: 0,
    condition: null,
    detailSpecs: {},
  };
}

export function getShortName(product) {
  return getDisplayData(product).shortName;
}

export function getWeeklyRate(dailyRate) {
  if (!dailyRate) return null;
  return dailyRate * 4;
}
